site_name: Fancy Dataclass
site_author: Jeremy Silver
repo_url: https://github.com/jeremander/fancy-dataclass

theme:
  name: material

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

nav:
  - index.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/
