site_name: Fancy Dataclass
site_author: Jeremy Silver
repo_url: https://github.com/jeremander/fancy-dataclass

theme:
  name: material

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            filters: ["!^_[^_]", "_replace"]
  - search
  - gen-files:
      scripts:
        # see https://mkdocstrings.github.io/recipes/
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

nav:
  - index.md
  - JSON conversion: json.md
  - SQL persistence: sql.md
  - CLI parsing: cli.md
  - Subprocess calls: subprocess.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/

watch:
  - fancy_dataclass
