[tool.poetry]
name = "fancy-dataclass"
version = "0.1.0"
description = "Classes for augmenting dataclasses with additional functionality."
authors = ["Jeremy Silver <jeremys@nessiness.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
