[tool.poetry]
name = "fancy-dataclass"
version = "0.1.0"
description = "Classes for augmenting dataclasses with additional functionality."
authors = ["Jeremy Silver <jeremys@nessiness.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^2.0.10"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.pytest.ini_options]
addopts = [
    "--capture=no",
    "--verbose",
    "--cov=fancy_dataclass"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
